source 'https://rubygems.org'

gem 'amqp'
gem 'adam_common', path: '../adam_common'
gem 'activesupport', require: nil
gem 'adhearsion', github: 'adhearsion', branch: :develop

# Translate Neuron
gem 'bing_translator'
gem 'iso-639'

# CRM Neuron
gem 'pipejump'

gem 'faraday'
gem 'faraday_middleware'

group :development, :test do
  gem 'rspec'
  gem 'guard'
  gem 'guard-rspec'
  gem 'evented-spec'
  gem 'webmock'
end
