#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'rbenv',             github: 'fnichol/chef-rbenv', ref: 'v0.7.2'
cookbook 'ruby_build',        github: 'fnichol/chef-ruby_build'
cookbook 'ejabberd',          github: 'mojolingo/ejabberd'
cookbook 'rabbitmq',          github: 'mojolingo/rabbitmq'
cookbook 'freeswitch',        github: 'mojolingo/freeswitch-cookbook', ref: 'da6e918da7719fad025b150ab1e65071735b80ec'

cookbook 'adam', path: 'adam_cookbook'
