#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'motd-tail'
cookbook 'git'
cookbook 'erlang'

cookbook 'chef-solo-search',  github: 'edelight/chef-solo-search'
cookbook 'mongodb',           github: 'edelight/chef-mongodb'
cookbook 'rbenv',             github: 'fnichol/chef-rbenv', ref: 'v0.7.2'
cookbook 'ruby_build',        github: 'fnichol/chef-ruby_build'
cookbook 'ejabberd',          github: 'mojolingo/ejabberd'
cookbook 'rabbitmq',          github: 'mojolingo/rabbitmq'
cookbook 'application_nginx', github: 'mojolingo/application_nginx'

cookbook 'adam', path: 'adam_cookbook'
