source 'https://rubygems.org'

gem 'rails', '~> 3.2'

gem 'mongoid', '~> 3.0'

gem 'airbrake'

gem 'unicorn'

gem 'devise'
gem 'omniauth'
gem 'omniauth-github'
gem 'omniauth-twitter'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1'
  gem 'coffee-rails', '~> 3.1'
  gem 'uglifier',     '>= 1.0.3'
  gem 'therubyracer'
  gem 'less-rails'
end

gem 'jquery-rails'
gem 'jquery-ui-rails'

gem 'haml'
gem 'haml-rails'

gem 'inherited_resources'
gem 'simple-navigation'
gem 'simple_form'
gem 'cocoon'

gem "twitter-bootstrap-rails"

gem 'bunny'

gem 'pipejump'

gem 'adam_signals', '~> 1.0'

gem 'ruby_jid'

group :development do
  gem 'debugger'

  # html2haml
  gem 'hpricot'
  gem 'ruby_parser'
end

group :development, :test do
  gem 'rspec-rails'

  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-rails-assets'
  gem 'terminal-notifier-guard'
end

group :test do
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'capybara'
  gem 'capybara-email'
  gem 'action_mailer_cache_delivery'
  gem 'poltergeist'
  gem 'webmock'
end
