Vagrant::Config.run do |config|
  config.vm.box       = "precise64"
  config.vm.host_name = "dev.adam.local"

  config.vm.customize do |vm|
    vm.name = "Adam Snark Rabbit Development Environment"
  end

  config.vm.network :hostonly, "192.168.33.100"
  config.vm.forward_port 3000, 3000

  config.vm.share_folder "adam", "/home/vagrant/adam", "..", nfs: true

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
    chef.roles_path = "roles"
    chef.data_bags_path = "data_bags"

    chef.add_role "dev"

    chef.json = {
      jabber_domain: 'adamrabbit.com',
      'rbenv' => {
        'user_installs' => [
          { 'user'    => 'vagrant',
            'rubies'  => ['1.9.3-p194'],
            'global'  => '1.9.3-p194',
            'gems'    => {
              '1.9.3-p194' => [
                { 'name' => 'bundler' },
                { 'name' => 'foreman' }
              ]
            }
          }
        ]
      }
    }

    chef.log_level = :debug
  end

  config.package.name = 'dev.adam.box'
end
