require 'berkshelf/vagrant'

Vagrant::Config.run do |config|
  config.vm.box       = "precise64"
  config.vm.box_url   = "http://files.vagrantup.com/precise64.box"
  config.vm.host_name = "local.adamrabbit.net"

  config.vm.network :hostonly, "192.168.33.100"

  config.vm.share_folder "adam", "/home/vagrant/adam", "..", nfs: true

  config.vm.provision :chef_solo do |chef|
    chef.roles_path = "roles"
    chef.data_bags_path = "data_bags"

    chef.add_role "dev"

    chef.json = {
      jabber_domain: 'local.adamrabbit.net',
      'rbenv' => {
        'user_installs' => [
          { 'user'    => 'vagrant',
            'rubies'  => ['1.9.3-p194'],
            'global'  => '1.9.3-p194',
            'gems'    => {
              '1.9.3-p194' => [
                { 'name' => 'bundler' },
                { 'name' => 'foreman' }
              ]
            }
          }
        ]
      },
      'adam' => {
        'deploy_key' => File.read('deploy_key')
      }
    }

    chef.log_level = :debug
  end

  config.package.name = 'dev.adam.box'
end
