source :rubygems

gem 'adhearsion', '~> 2.0'
gem 'adhearsion-reporter', '~> 2.0'

gem 'adhearsion-xmpp', '~> 1.0'
gem 'blather', :git => 'git://github.com/sprsquish/blather.git', :branch => :develop

gem 'httparty'

group :development do
  gem 'debugger'
end

group :development, :test do
  gem 'rspec'
  gem 'mocha'

  gem 'guard'
  gem 'guard-rspec'
  gem 'ruby_gntp'
end
