#!/usr/bin/env rake

require File.expand_path('../config/environment',  __FILE__)

Bundler.require :development

require 'adhearsion/tasks'

require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec)
