source 'https://rubygems.org'

gem 'adhearsion', '~> 2.4'
gem 'adhearsion-asr'
gem 'adhearsion-reporter', '~> 2.0'

gem 'att_speech', github: 'emcgee/att_speech', branch: 'master'

group :development, :test do
  gem 'rspec'

  gem 'guard'
  gem 'guard-rspec'
  gem 'ruby_gntp'
end
