source 'https://rubygems.org'

gem 'adhearsion', github: 'adhearsion', branch: 'develop'
gem 'adhearsion-reporter', '~> 2.0'
gem 'blather'
gem 'amqp'
gem 'adam_common', path: '../adam_common'

group :development, :test do
  gem 'rspec'
  gem 'guard'
  gem 'guard-rspec'
end
