source "http://rubygems.org"

gem 'blather'
gem 'eventmachine', '0.12.10'
gem 'amqp'
gem 'adam_common', path: '../adam_common'

group :development, :test do
  gem 'rspec'
  gem 'guard'
  gem 'guard-rspec'
end
