source :rubygems

gem 'rails', '~> 3.2'

gem 'mongoid',  '~> 2.3'
gem 'bson_ext', '~> 1.4'

gem 'airbrake'

gem 'devise'
gem 'omniauth'
gem 'omniauth-github'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1'
  gem 'coffee-rails', '~> 3.1'
  gem 'uglifier',     '>= 1.0.3'
end

gem 'jquery-rails'

gem 'haml'
gem 'haml-rails'

gem 'inherited_resources'
gem 'simple-navigation'
gem 'simple_form'

# Use unicorn as the web server
# gem 'unicorn'

gem "twitter-bootstrap-rails"

group :development do
  gem 'debugger'

  # html2haml
  gem 'hpricot'
  gem 'ruby_parser'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'jasmine-rails'

  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-rails-assets'
  gem 'guard-jasmine-headless-webkit'
  gem 'ruby_gntp'
end

group :test do
  gem 'mocha'
  gem 'rspec-rails-mocha', :require => false
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'capybara'
  gem 'poltergeist'
end
